USE MASTER
GO

CREATE DATABASE SistemaPedidos
GO

USE SistemaPedidos
GO

--CREACION DE TABLAS
CREATE TABLE DISTRITOS(
    COD_DIS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOM_DIS VARCHAR(50) NOT NULL
)

CREATE TABLE CLIENTES(
    IDE_CLI INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COD_CLI AS ('CL'+RIGHT('00000'+CONVERT(VARCHAR,IDE_CLI),5)),
    NOM_CLI VARCHAR(50) NOT NULL,
    DNI_CLI CHAR(8) NOT NULL,
    TEL_CLI CHAR(9) NOT NULL,
    MAIL_CLI VARCHAR(100) NOT NULL,
    FEC_REG DATE NOT NULL DEFAULT CONVERT(VARCHAR,GETDATE(),103),
    DIR_CLI VARCHAR(150) NOT NULL,
    COD_DIS INT NOT NULL,
    FOREIGN KEY (COD_DIS) REFERENCES DISTRITOS(COD_DIS)
)

CREATE TABLE ROLES(
    COD_ROL INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOM_ROL VARCHAR(25) NOT NULL
)

CREATE TABLE USUARIOS(
    IDE_USU INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COD_USU AS ('US'+RIGHT('00000'+CONVERT(VARCHAR,IDE_USU),5)),
    COD_ROL INT NOT NULL,
    NOM_USU VARCHAR(100) NOT NULL,
    DNI_USU CHAR(8) NOT NULL,
    MAIL_USU VARCHAR(70) NOT NULL,
    PASS_USU AS ('D'+RIGHT(DNI_USU,9)),
    FOREIGN KEY (COD_ROL) REFERENCES ROLES(COD_ROL)
)

CREATE TABLE PERSONAL_ENTREGA(
    IDE_MOT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COD_MOT AS ('MT'+RIGHT('00000'+CONVERT(VARCHAR,IDE_MOT),5)),
    NOM_MOT VARCHAR(100) NOT NULL,
    DNI_MOT CHAR(8) NOT NULL,
    NRO_LIC CHAR(9) NOT NULL,
    TIPO_LIC VARCHAR(10) NOT NULL,
	TIP_VEH VARCHAR(50) NOT NULL,
	MAT_VEH CHAR(8) NOT NULL,
	MOD_VEH VARCHAR(20) NOT NULL,
	MAR_VEH VARCHAR(25) NOT NULL,
    FEC_ING DATE NOT NULL DEFAULT CONVERT(VARCHAR,GETDATE(),103),
    EST_MOT INT NOT NULL DEFAULT 1
)

CREATE TABLE PLATOS(
    IDE_PLA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COD_PLA AS ('PL'+RIGHT('00000'+CONVERT(VARCHAR,IDE_PLA),5)),
    NOM_PLA VARCHAR(100) NOT NULL,
    PRE_PLA DECIMAL(10,2) NOT NULL
)

CREATE TABLE PEDIDOS(
    IDE_PED INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COD_PED AS ('PD'+RIGHT('00000'+CONVERT(VARCHAR,IDE_PED),5)),
	IDE_PLA INT NOT NULL,
    IDE_CLI INT NOT NULL,
	CANT_PED INT NOT NULL,
    IGV_PED DECIMAL(10,2) NOT NULL,
    TOT_PED DECIMAL(10,2) NOT NULL,
    IDE_USU INT NOT NULL,
    FEC_PED DATE NOT NULL DEFAULT CONVERT(varchar,GETDATE(),103),
    EST_PED INT NOT NULL DEFAULT 0,
    FOREIGN KEY (IDE_USU) REFERENCES USUARIOS(IDE_USU),
    FOREIGN KEY (IDE_CLI) REFERENCES CLIENTES(IDE_CLI),
	FOREIGN KEY (IDE_PLA) REFERENCES PLATOS(IDE_PLA)
)

CREATE TABLE ASIGNACIONES(
	IDE_ASG INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COD_ASG AS ('DT'+RIGHT('00000'+CONVERT(VARCHAR,IDE_ASG),5)),
	IDE_PED INT NOT NULL,
	IDE_MOT INT NOT NULL,
	FOREIGN KEY (IDE_PED) REFERENCES PEDIDOS(IDE_PED),
    FOREIGN KEY (IDE_MOT) REFERENCES PERSONAL_ENTREGA(IDE_MOT)
)

CREATE TABLE HISTORIAL_PEDIDOS(
    IDE_HIS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COD_HIS AS ('HS'+RIGHT('00000'+CONVERT(VARCHAR,IDE_HIS),5)),
    IDE_PED INT NOT NULL,
    NOTA_PED VARCHAR(MAX) NOT NULL,
    FOREIGN KEY (IDE_PED) REFERENCES PEDIDOS(IDE_PED)
)

--ALTERANDO TABLA PEDIDOS PARA AGREGAR EL SUBTOTAL
ALTER TABLE PEDIDOS
    ADD SBT_PED DECIMAL(10,2) NULL
GO

--ALTERANDO TABLA HISTORIAL PARA AGREGAR EL MOTORIZADO
ALTER TABLE HISTORIAL_PEDIDOS
    ADD IDE_MOT INT NULL,
	FOREIGN KEY (IDE_MOT) REFERENCES PERSONAL_ENTREGA(IDE_MOT)
GO

--INSERTANDO DATOS DE PRUEBA EN LAS TABLAS

--TABLA DISTRITOS
INSERT INTO DISTRITOS
VALUES
('LIMA'),
('ANCON'),
('ATE'),
('BARRANCO'),
('BREÑA'),
('CARABAYLLO'),
('CHACLACAYO'),
('CHORRILLOS'),
('CIENEGUILLA'),
('COMAS'),
('EL AGUSTINO'),
('INDEPENDENCIA'),
('JESUS MARIA'),
('LA MOLINA'),
('LA VICTORIA'),
('LINCE'),
('LOS OLIVOS'),
('LURIGANCHO'),
('LURIN'),
('MAGDALENA DEL MAR'),
('MIRAFLORES'),
('PACHACAMAC'),
('PUCUSANA'),
('PUENTE PIEDRA'),
('PUNTA HERMOSA'),
('PUNTA NEGRA'),
('RIMAC'),
('SAN BARTOLO'),
('SAN BORJA'),
('SAN ISIDRO'),
('SAN JUAN DE LURIGANCHO'),
('SAN JUAN DE MIRAFLORES'),
('SAN LUIS'),
('SAN MARTIN DE PORRES'),
('SAN MIGUEL'),
('SANTA ANITA'),
('SANTA MARIA DEL MAR'),
('SANTA ROSA'),
('SANTIAGO DE SURCO'),
('SURQUILLO'),
('VILLA EL SALVADOR'),
('VILLA MARIA DEL TRIUNFO');

--TABLA ROLES
INSERT INTO ROLES
VALUES('ADMINISTRADOR'),('EMPLEADO')

--TABLA USUARIOS
INSERT INTO USUARIOS
VALUES (1,'JORGE MENDOZA','20202020','jorge@hotmail.com')

--TABLA CLIENTES
INSERT INTO CLIENTES(NOM_CLI,DNI_CLI,TEL_CLI,MAIL_CLI,DIR_CLI,COD_DIS)
VALUES ('LUCERO ROMERO','10101010','987654321','lucerito@gmail.com','AV. LOS ANGELES 238',3)

--TABLA MOTORIZADO
INSERT INTO PERSONAL_ENTREGA(NOM_MOT,DNI_MOT,NRO_LIC,TIPO_LIC,TIP_VEH,MAT_VEH,MOD_VEH,MAR_VEH)
VALUES ('MARCO CASTRO','30303030','Q30303030','B-IIB','MOTO LINEAL','XFH-630','ECO FINITI 150','SSENDA')

INSERT INTO PLATOS
VALUES ('ARROZ A LA CUBANA',5.50);

SELECT * FROM PLATOS;

INSERT INTO PEDIDOS(IDE_PLA,IDE_CLI,CANT_PED,IGV_PED,TOT_PED,IDE_USU)
VALUES(1,1,2,((5.50*2)*0.18),(5.50*2+((5.50*2)*0.18)),1);
