USE SistemaPedidos
GO
--PROCEDIMIENTOS ALMACENADOS

--PROCEDIMIENTOS ALMACENADOS PARA LA TABLA CLIENTES

----LISTAR
	CREATE PROCEDURE SP_LISTARCLIENTE
	AS
	BEGIN
		SELECT IDE_CLI ID,COD_CLI CODIGO,NOM_CLI NOMBRES,DNI_CLI DNI,TEL_CLI TELEFONO,MAIL_CLI CORREO,
		       FEC_REG "FECHA REGISTRO",DIR_CLI DIRECCION,DI.NOM_DIS DISTRITO
		FROM CLIENTES CL
		INNER JOIN DISTRITOS DI ON CL.COD_DIS = DI.COD_DIS;
	END;
	GO

----INSERTAR
	CREATE PROCEDURE SP_INSERTARCLIENTE
		@NOM_CLI VARCHAR(50),
		@DNI_CLI CHAR(8),
		@TEL_CLI CHAR(9),
		@MAIL_CLI VARCHAR(100),
		@DIR_CLI VARCHAR(150),
		@COD_DIS INT
	AS
	BEGIN
		INSERT INTO CLIENTES(NOM_CLI,DNI_CLI,TEL_CLI,MAIL_CLI,DIR_CLI,COD_DIS)
		VALUES(@NOM_CLI,@DNI_CLI,@TEL_CLI,@MAIL_CLI,@DIR_CLI,@COD_DIS);
	END;
	GO

----MODIFICAR
	CREATE PROCEDURE SP_MODIFICARCLIENTE
		@IDE_CLI INT,
		@NOM_CLI VARCHAR(50),
		@DNI_CLI CHAR(8),
		@TEL_CLI CHAR(9),
		@MAIL_CLI VARCHAR(100),
		@DIR_CLI VARCHAR(150),
		@COD_DIS INT
	AS
	BEGIN
		UPDATE CLIENTES SET
			NOM_CLI = @NOM_CLI,
			DNI_CLI = @DNI_CLI,
			TEL_CLI = @TEL_CLI,
			MAIL_CLI = @MAIL_CLI,
			DIR_CLI = @DIR_CLI,
			COD_DIS = @COD_DIS
			WHERE IDE_CLI = @IDE_CLI
	END;
	GO

----ELIMINAR
	CREATE PROCEDURE SP_ELIMINARCLIENTE
		@IDE_CLI INT
	AS
	BEGIN
		DELETE FROM CLIENTES
		WHERE IDE_CLI = @IDE_CLI;
	END;
	GO

----LISTAR DISTRITOS
	CREATE PROCEDURE SP_LISTARDISTRITOS
	AS
	BEGIN
		SELECT COD_DIS,NOM_DIS
		FROM DISTRITOS;
	END;
	GO

--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
select * from USUARIOS
--PROCEDIMIENTOS ALMACENADOS PARA LA TABLA USUARIOS

----LISTAR
	CREATE PROCEDURE SP_LISTARUSUARIOS
	AS
	BEGIN
		SELECT IDE_USU ID,COD_USU CODIGO,RO.NOM_ROL ROL,NOM_USU NOMBRES,DNI_USU DNI,
		       MAIL_USU CORREO
		FROM USUARIOS US
		INNER JOIN ROLES RO ON US.COD_ROL = RO.COD_ROL;
	END;
	GO

----INSERTAR
	CREATE PROCEDURE SP_INSERTARUSUARIO
		@COD_ROL INT,
		@NOM_USU VARCHAR(100),
		@DNI_USU CHAR(8),
		@MAIL_USU VARCHAR(70)
	AS
	BEGIN
		INSERT INTO USUARIOS
		VALUES (@COD_ROL,@NOM_USU,@DNI_USU,@MAIL_USU);
	END;
	GO

----ACTUALIZAR
	CREATE PROCEDURE SP_MODIFICARUSUARIO
		@IDE_USU INT,
		@COD_ROL INT,
		@NOM_USU VARCHAR(100),
		@DNI_USU CHAR(8),
		@MAIL_USU VARCHAR(70)
	AS
	BEGIN
		UPDATE USUARIOS SET
			COD_ROL = @COD_ROL,
			NOM_USU = @NOM_USU,
			DNI_USU = @DNI_USU,
			MAIL_USU = @MAIL_USU
			WHERE IDE_USU = @IDE_USU;
	END;
	GO

----ELIMINAR
	CREATE PROCEDURE SP_ELIMINARUSUARIO
		@IDE_USU INT
	AS
	BEGIN
		DELETE FROM USUARIOS
		WHERE IDE_USU = @IDE_USU;
	END;
	GO

----LOGIN USUARIO
	CREATE PROCEDURE SP_LOGIN
		@MAIL_USU VARCHAR(70),
		@PASS_USU VARCHAR(9)
	AS
	BEGIN
		SELECT U.IDE_USU,R.COD_ROL,R.NOM_ROL,U.NOM_USU,U.DNI_USU,U.MAIL_USU,U.PASS_USU
		FROM USUARIOS U
		INNER JOIN ROLES R ON U.COD_ROL = R.COD_ROL
		WHERE MAIL_USU = @MAIL_USU AND PASS_USU = @PASS_USU;
	END;
	GO

----LISTAR ROLES
	CREATE PROCEDURE SP_LISTARROLES
	AS
	BEGIN
		SELECT COD_ROL,NOM_ROL
		FROM ROLES;
	END;
	GO
	
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

--PROCEDIMIENTOS ALMACENADOS PARA LA TABLA PERSONAL ENTREGA

----LISTAR
	CREATE PROCEDURE SP_LISTARPERSONALENTREGA
	AS
	BEGIN
		SELECT IDE_MOT ID,COD_MOT CODIGO,NOM_MOT NOMBRES,DNI_MOT DNI,NRO_LIC "N° LICENCIA",TIPO_LIC "TIPO LICENCIA",
			   TIP_VEH "TIPO VEHICULO",MAT_VEH PLACA,MOD_VEH MODELO,MAR_VEH MARCA,FEC_ING "FECHA DE INGRESO",
			   CASE
					WHEN EST_MOT = 0 THEN 'DESPEDIDO'
					WHEN EST_MOT = 1 THEN 'DISPONIBLE'
					WHEN EST_MOT = 2 THEN 'OCUPADO'
				END AS ESTADO
		FROM PERSONAL_ENTREGA
		WHERE EST_MOT != 0;
	END;
	GO

----INSERTAR
	CREATE PROCEDURE SP_INSERTARPERSONALENTREGA
		@NOM_MOT VARCHAR(100),
		@DNI_MOT CHAR(8),
		@NRO_LIC CHAR(9),
		@TIPO_LIC VARCHAR(10),
		@TIP_VEH VARCHAR(50),
		@MAT_VEH CHAR(8),
		@MOD_VEH VARCHAR(20),
		@MAR_VEH VARCHAR(25)
	AS
	BEGIN
		INSERT INTO PERSONAL_ENTREGA(NOM_MOT,DNI_MOT,NRO_LIC,TIPO_LIC,TIP_VEH,MAT_VEH,MOD_VEH,MAR_VEH)
		VALUES (@NOM_MOT,@DNI_MOT,@NRO_LIC,@TIPO_LIC,@TIP_VEH,@MAT_VEH,@MOD_VEH,@MAR_VEH);
	END;
	GO

----ACTUALIZAR
	CREATE PROCEDURE SP_MODIFICARPERSONALENTREGA
		@IDE_MOT INT,
		@NOM_MOT VARCHAR(100),
		@DNI_MOT CHAR(8),
		@NRO_LIC CHAR(9),
		@TIPO_LIC VARCHAR(10),
		@TIP_VEH VARCHAR(50),
		@MAT_VEH CHAR(8),
		@MOD_VEH VARCHAR(20),
		@MAR_VEH VARCHAR(25)
	AS
	BEGIN
		UPDATE PERSONAL_ENTREGA SET
			NOM_MOT = @NOM_MOT,
			DNI_MOT = @DNI_MOT,
			NRO_LIC = @NRO_LIC,
			TIPO_LIC = @TIPO_LIC,
			TIP_VEH = @TIP_VEH,
			MAT_VEH = @MAT_VEH,
			MOD_VEH = @MOD_VEH,
			MAR_VEH = @MAR_VEH
			WHERE IDE_MOT = @IDE_MOT;
	END;
	GO

----ELIMINAR
	CREATE PROCEDURE SP_ELIMINARPERSONALENTREGA
		@IDE_MOT INT
	AS
	BEGIN
		UPDATE PERSONAL_ENTREGA SET
			EST_MOT = 0
			WHERE IDE_MOT = @IDE_MOT;
	END;
	GO

----LISTAR COMBOBOX
	CREATE PROCEDURE SP_LISTARPERSONALENTREGADISPONIBLE
	AS
	BEGIN
		SELECT IDE_MOT CODIGO,NOM_MOT NOMBRES
		FROM PERSONAL_ENTREGA
		WHERE EST_MOT = 1;
	END;
	GO

--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

--PROCEDIMIENTOS ALMACENADOS PARA LA TABLA MENUS

----LISTAR
	CREATE PROCEDURE SP_LISTARPLATOS
	AS
	BEGIN
		SELECT IDE_PLA ID,COD_PLA CODIGO,NOM_PLA NOMBRE,PRE_PLA PRECIO
		FROM PLATOS;
	END;
	GO

----INSERTAR
	CREATE PROCEDURE SP_INSERTARPLATO
		@NOM_PLA VARCHAR(100),
		@PRE_PLA DECIMAL(10,2)
	AS
	BEGIN
		INSERT INTO PLATOS
		VALUES (@NOM_PLA,@PRE_PLA);
	END;
	GO

----ACTUALIZAR
	CREATE PROCEDURE SP_MODIFICARPLATO
		@IDE_PLA INT,
		@NOM_PLA VARCHAR(100),
		@PRE_PLA DECIMAL(10,2)
	AS
	BEGIN
		UPDATE PLATOS SET
			NOM_PLA = @NOM_PLA,
			PRE_PLA = @PRE_PLA
			WHERE IDE_PLA = @IDE_PLA;
	END;
	GO

----ELIMINAR
	CREATE PROCEDURE SP_ELIMINARPLATO
		@IDE_PLA INT
	AS
	BEGIN
		DELETE FROM PLATOS
		WHERE IDE_PLA = @IDE_PLA;
	END;
	GO

--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

--PROCEDIMIENTOS ALMACENADOS PARA LA TABLA PEDIDOS

----LISTAR
	CREATE PROCEDURE SP_LISTARPEDIDOS
	AS
	BEGIN
		SELECT IDE_PED ID,COD_PED CODIGO,CL.NOM_CLI CLIENTE,CL.DIR_CLI "DIRECCION CLIENTE",DI.NOM_DIS DISTRITO,PL.NOM_PLA "NOMBRE MENU",PL.PRE_PLA PRECIO,
			   CANT_PED CANTIDAD,SBT_PED SUBTOTAL,IGV_PED IMPUESTO,TOT_PED "TOTAL A PAGAR",US.NOM_USU USUARIO,FEC_PED "FECHA PEDIDO",
			   CASE
					WHEN EST_PED = 0 THEN 'PENDIENTE'
					WHEN EST_PED = 1 THEN 'EN RUTA'
					WHEN EST_PED = 2 THEN 'FINALIZADO'
					WHEN EST_PED = 3 THEN 'ANULADO'
				END AS ESTADO
		FROM PEDIDOS PE
		INNER JOIN PLATOS PL ON PE.IDE_PLA = PL.IDE_PLA
		INNER JOIN CLIENTES CL ON PE.IDE_CLI = CL.IDE_CLI
		INNER JOIN USUARIOS US ON PE.IDE_USU = US.IDE_USU
		INNER JOIN DISTRITOS DI ON CL.COD_DIS = DI.COD_DIS
		ORDER BY EST_PED DESC;
	END;
	GO

----INSERTAR
	CREATE PROCEDURE SP_INSERTARPEDIDO
		@IDE_PLA INT,
		@IDE_CLI INT,
		@CANT_PED INT,
		@IGV_PED DECIMAL(10,2),
		@TOT_PED DECIMAL(10,2),
		@IDE_USU INT,
		@SBT_PED DECIMAL(10,2)
	AS
	BEGIN
		INSERT INTO PEDIDOS(IDE_PLA,IDE_CLI,CANT_PED,IGV_PED,TOT_PED,IDE_USU,SBT_PED)
		VALUES(@IDE_PLA,@IDE_CLI,@CANT_PED,@IGV_PED,@TOT_PED,@IDE_USU,@SBT_PED);
	END;
	GO

----ELIMINAR
	CREATE PROCEDURE SP_ELIMINARPEDIDO
		@IDE_PED INT
	AS
	BEGIN
		UPDATE PEDIDOS SET EST_PED = 3
		WHERE IDE_PED = @IDE_PED;
	END;
	GO

----LISTAR PARA PRINCIPAL
CREATE PROCEDURE SP_LISTAPEDIDOSPENDIENTES
	AS
	BEGIN
		SELECT IDE_PED ID,COD_PED CODIGO,CL.NOM_CLI CLIENTE,CL.DIR_CLI "DIRECCION CLIENTE",DI.NOM_DIS DISTRITO,PL.NOM_PLA "NOMBRE MENU",PL.PRE_PLA PRECIO,
			   CANT_PED CANTIDAD,SBT_PED SUBTOTAL,IGV_PED IMPUESTO,TOT_PED "TOTAL A PAGAR",US.NOM_USU USUARIO,FEC_PED "FECHA PEDIDO",
			   CASE
					WHEN EST_PED = 0 THEN 'PENDIENTE'
					WHEN EST_PED = 1 THEN 'EN RUTA'
					WHEN EST_PED = 2 THEN 'FINALIZADO'
					WHEN EST_PED = 3 THEN 'ANULADO'
				END EST_PED
		FROM PEDIDOS PE
		INNER JOIN PLATOS PL ON PE.IDE_PLA = PL.IDE_PLA
		INNER JOIN CLIENTES CL ON PE.IDE_CLI = CL.IDE_CLI
		INNER JOIN USUARIOS US ON PE.IDE_USU = US.IDE_USU
		INNER JOIN DISTRITOS DI ON CL.COD_DIS = DI.COD_DIS
		WHERE EST_PED=0;
	END;
	GO

--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

--PROCEDIMIENTOS ALMACENADOS PARA LA TABLA ASIGNACIONES

----LISTAR
	CREATE PROCEDURE SP_LISTARASIGNACIONES
	AS
	BEGIN
		SELECT PE.IDE_PED "ID PEDIDO",PE.COD_PED "CODIGO PEDIDO",PL.NOM_PLA MENU,PE.CANT_PED CANTIDAD,PE.TOT_PED "PRECIO TOTAL",
			   P.IDE_MOT "ID MOTORIZADO",P.COD_MOT "CODIGO MOTORIZADO",P.NOM_MOT "NOMBRE MOTORIZADO"
		FROM ASIGNACIONES A
		INNER JOIN PEDIDOS PE ON A.IDE_PED = PE.IDE_PED
		INNER JOIN PERSONAL_ENTREGA P ON A.IDE_MOT = P.IDE_MOT
		INNER JOIN PLATOS PL ON PE.IDE_PLA = PL.IDE_PLA;
	END;
	GO

----INSERTAR
	CREATE PROCEDURE SP_INSERTARASIGNACION
		@IDE_PED INT,
		@IDE_MOT INT
	AS
	BEGIN
		INSERT INTO ASIGNACIONES(IDE_PED,IDE_MOT)
		VALUES (@IDE_PED,@IDE_MOT)
		UPDATE PEDIDOS SET EST_PED = 1 WHERE IDE_PED = @IDE_PED;
		UPDATE PERSONAL_ENTREGA SET EST_MOT = 2 WHERE IDE_MOT = @IDE_MOT;
	END;
	GO

----LISTAR ASIGNACIONES EN RUTA
	CREATE PROCEDURE SP_LISTARASIGNACIONESPENDIENTES
	AS
	BEGIN
		SELECT PE.IDE_PED "ID PEDIDO",PE.COD_PED "CODIGO PEDIDO",PL.NOM_PLA MENU,PE.CANT_PED CANTIDAD,PE.TOT_PED "PRECIO TOTAL",
			   P.IDE_MOT "ID MOTORIZADO",P.COD_MOT "CODIGO MOTORIZADO",P.NOM_MOT "NOMBRE MOTORIZADO"
		FROM ASIGNACIONES A
		INNER JOIN PEDIDOS PE ON A.IDE_PED = PE.IDE_PED
		INNER JOIN PERSONAL_ENTREGA P ON A.IDE_MOT = P.IDE_MOT
		INNER JOIN PLATOS PL ON PE.IDE_PLA = PL.IDE_PLA
		WHERE PE.EST_PED = 1;
	END;
	GO

--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

--PROCEDIMIENTO ALMACENADO PARA REGISTRAR HISTORIAL DE PEDIDOS

----LISTAR
	CREATE PROCEDURE SP_LISTARHISTORIAL
	AS
	BEGIN
		SELECT COD_HIS CODIGO,PE.IDE_PED "ID PED",PE.COD_PED PEDIDO,PE.FEC_PED FECHA,PS.IDE_MOT "ID MOT",PS.NOM_MOT MOTORIZADO,
			   NOTA_PED "OBSERVACIONES",US.NOM_USU "REGISTRADO POR"
		FROM HISTORIAL_PEDIDOS HP
		INNER JOIN PEDIDOS PE ON HP.IDE_PED = PE.IDE_PED
		INNER JOIN USUARIOS US ON PE.IDE_USU = US.IDE_USU
		INNER JOIN PERSONAL_ENTREGA PS ON HP.IDE_MOT = PS.IDE_MOT;
	END;
	GO

----INSERTAR
	CREATE PROCEDURE SP_INSERTARHISTORIAL
		@IDE_PED INT,
		@NOTA_PED VARCHAR(MAX),
		@IDE_MOT INT
	AS
	BEGIN
		INSERT INTO HISTORIAL_PEDIDOS(IDE_PED,NOTA_PED,IDE_MOT)
		VALUES (@IDE_PED,@NOTA_PED,@IDE_MOT)
		UPDATE PEDIDOS SET EST_PED = 2 WHERE IDE_PED = @IDE_PED;
		UPDATE PERSONAL_ENTREGA SET EST_MOT = 1 WHERE IDE_MOT = @IDE_MOT;
	END;
	GO