//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazGUI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idrolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrerolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomusuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dniusuario {
            get {
                return this.dniusuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.dniusuarioField, value) != true)) {
                    this.dniusuarioField = value;
                    this.RaisePropertyChanged("dniusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idrol {
            get {
                return this.idrolField;
            }
            set {
                if ((this.idrolField.Equals(value) != true)) {
                    this.idrolField = value;
                    this.RaisePropertyChanged("idrol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idusuario {
            get {
                return this.idusuarioField;
            }
            set {
                if ((this.idusuarioField.Equals(value) != true)) {
                    this.idusuarioField = value;
                    this.RaisePropertyChanged("idusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrerol {
            get {
                return this.nombrerolField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrerolField, value) != true)) {
                    this.nombrerolField = value;
                    this.RaisePropertyChanged("nombrerol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomusuario {
            get {
                return this.nomusuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nomusuarioField, value) != true)) {
                    this.nomusuarioField = value;
                    this.RaisePropertyChanged("nomusuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iddistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dnicliente {
            get {
                return this.dniclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.dniclienteField, value) != true)) {
                    this.dniclienteField = value;
                    this.RaisePropertyChanged("dnicliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((this.idclienteField.Equals(value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iddistrito {
            get {
                return this.iddistritoField;
            }
            set {
                if ((this.iddistritoField.Equals(value) != true)) {
                    this.iddistritoField = value;
                    this.RaisePropertyChanged("iddistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomcliente {
            get {
                return this.nomclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nomclienteField, value) != true)) {
                    this.nomclienteField = value;
                    this.RaisePropertyChanged("nomcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Motorizado", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Motorizado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dnimotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idmotorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombremotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrolicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipolicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipovehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dnimot {
            get {
                return this.dnimotField;
            }
            set {
                if ((object.ReferenceEquals(this.dnimotField, value) != true)) {
                    this.dnimotField = value;
                    this.RaisePropertyChanged("dnimot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idmotorizado {
            get {
                return this.idmotorizadoField;
            }
            set {
                if ((this.idmotorizadoField.Equals(value) != true)) {
                    this.idmotorizadoField = value;
                    this.RaisePropertyChanged("idmotorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                if ((object.ReferenceEquals(this.marcaField, value) != true)) {
                    this.marcaField = value;
                    this.RaisePropertyChanged("marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula {
            get {
                return this.matriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.matriculaField, value) != true)) {
                    this.matriculaField = value;
                    this.RaisePropertyChanged("matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                if ((object.ReferenceEquals(this.modeloField, value) != true)) {
                    this.modeloField = value;
                    this.RaisePropertyChanged("modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombremot {
            get {
                return this.nombremotField;
            }
            set {
                if ((object.ReferenceEquals(this.nombremotField, value) != true)) {
                    this.nombremotField = value;
                    this.RaisePropertyChanged("nombremot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrolicencia {
            get {
                return this.nrolicenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.nrolicenciaField, value) != true)) {
                    this.nrolicenciaField = value;
                    this.RaisePropertyChanged("nrolicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipolicencia {
            get {
                return this.tipolicenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipolicenciaField, value) != true)) {
                    this.tipolicenciaField = value;
                    this.RaisePropertyChanged("tipolicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipovehiculo {
            get {
                return this.tipovehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipovehiculoField, value) != true)) {
                    this.tipovehiculoField = value;
                    this.RaisePropertyChanged("tipovehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plato", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Plato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idmenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombremenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float preciomenuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idmenu {
            get {
                return this.idmenuField;
            }
            set {
                if ((this.idmenuField.Equals(value) != true)) {
                    this.idmenuField = value;
                    this.RaisePropertyChanged("idmenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombremenu {
            get {
                return this.nombremenuField;
            }
            set {
                if ((object.ReferenceEquals(this.nombremenuField, value) != true)) {
                    this.nombremenuField = value;
                    this.RaisePropertyChanged("nombremenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float preciomenu {
            get {
                return this.preciomenuField;
            }
            set {
                if ((this.preciomenuField.Equals(value) != true)) {
                    this.preciomenuField = value;
                    this.RaisePropertyChanged("preciomenu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idpedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idplatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float igvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float subtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float totalpedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((this.idclienteField.Equals(value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idpedido {
            get {
                return this.idpedidoField;
            }
            set {
                if ((this.idpedidoField.Equals(value) != true)) {
                    this.idpedidoField = value;
                    this.RaisePropertyChanged("idpedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idplato {
            get {
                return this.idplatoField;
            }
            set {
                if ((this.idplatoField.Equals(value) != true)) {
                    this.idplatoField = value;
                    this.RaisePropertyChanged("idplato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idusuario {
            get {
                return this.idusuarioField;
            }
            set {
                if ((this.idusuarioField.Equals(value) != true)) {
                    this.idusuarioField = value;
                    this.RaisePropertyChanged("idusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float igv {
            get {
                return this.igvField;
            }
            set {
                if ((this.igvField.Equals(value) != true)) {
                    this.igvField = value;
                    this.RaisePropertyChanged("igv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float subtotal {
            get {
                return this.subtotalField;
            }
            set {
                if ((this.subtotalField.Equals(value) != true)) {
                    this.subtotalField = value;
                    this.RaisePropertyChanged("subtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float totalpedido {
            get {
                return this.totalpedidoField;
            }
            set {
                if ((this.totalpedidoField.Equals(value) != true)) {
                    this.totalpedidoField = value;
                    this.RaisePropertyChanged("totalpedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asignacion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Asignacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idmotorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idpedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idmotorizado {
            get {
                return this.idmotorizadoField;
            }
            set {
                if ((this.idmotorizadoField.Equals(value) != true)) {
                    this.idmotorizadoField = value;
                    this.RaisePropertyChanged("idmotorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idpedido {
            get {
                return this.idpedidoField;
            }
            set {
                if ((this.idpedidoField.Equals(value) != true)) {
                    this.idpedidoField = value;
                    this.RaisePropertyChanged("idpedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Historial", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Historial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idmotorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idpedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idmotorizado {
            get {
                return this.idmotorizadoField;
            }
            set {
                if ((this.idmotorizadoField.Equals(value) != true)) {
                    this.idmotorizadoField = value;
                    this.RaisePropertyChanged("idmotorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idpedido {
            get {
                return this.idpedidoField;
            }
            set {
                if ((this.idpedidoField.Equals(value) != true)) {
                    this.idpedidoField = value;
                    this.RaisePropertyChanged("idpedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nota {
            get {
                return this.notaField;
            }
            set {
                if ((object.ReferenceEquals(this.notaField, value) != true)) {
                    this.notaField = value;
                    this.RaisePropertyChanged("nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUsuarios")]
    public interface IUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/Login", ReplyAction="http://tempuri.org/IUsuarios/LoginResponse")]
        bool Login(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/Login", ReplyAction="http://tempuri.org/IUsuarios/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/LISTAUSUARIOS", ReplyAction="http://tempuri.org/IUsuarios/LISTAUSUARIOSResponse")]
        System.Data.DataSet LISTAUSUARIOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/LISTAUSUARIOS", ReplyAction="http://tempuri.org/IUsuarios/LISTAUSUARIOSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTAUSUARIOSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/LISTAROLES", ReplyAction="http://tempuri.org/IUsuarios/LISTAROLESResponse")]
        System.Data.DataSet LISTAROLES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/LISTAROLES", ReplyAction="http://tempuri.org/IUsuarios/LISTAROLESResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTAROLESAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/NUEVOUSUARIO", ReplyAction="http://tempuri.org/IUsuarios/NUEVOUSUARIOResponse")]
        void NUEVOUSUARIO(InterfazGUI.ServiceReference1.Usuario objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/NUEVOUSUARIO", ReplyAction="http://tempuri.org/IUsuarios/NUEVOUSUARIOResponse")]
        System.Threading.Tasks.Task NUEVOUSUARIOAsync(InterfazGUI.ServiceReference1.Usuario objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ACTUALIZAUSUARIO", ReplyAction="http://tempuri.org/IUsuarios/ACTUALIZAUSUARIOResponse")]
        void ACTUALIZAUSUARIO(InterfazGUI.ServiceReference1.Usuario objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ACTUALIZAUSUARIO", ReplyAction="http://tempuri.org/IUsuarios/ACTUALIZAUSUARIOResponse")]
        System.Threading.Tasks.Task ACTUALIZAUSUARIOAsync(InterfazGUI.ServiceReference1.Usuario objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ELIMINAUSUARIO", ReplyAction="http://tempuri.org/IUsuarios/ELIMINAUSUARIOResponse")]
        void ELIMINAUSUARIO(InterfazGUI.ServiceReference1.Usuario objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ELIMINAUSUARIO", ReplyAction="http://tempuri.org/IUsuarios/ELIMINAUSUARIOResponse")]
        System.Threading.Tasks.Task ELIMINAUSUARIOAsync(InterfazGUI.ServiceReference1.Usuario objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/obtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/obtenerUsuarioResponse")]
        System.Data.DataTable obtenerUsuario(InterfazGUI.ServiceReference1.Usuario objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/obtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/obtenerUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> obtenerUsuarioAsync(InterfazGUI.ServiceReference1.Usuario objP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosChannel : InterfazGUI.ServiceReference1.IUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<InterfazGUI.ServiceReference1.IUsuarios>, InterfazGUI.ServiceReference1.IUsuarios {
        
        public UsuariosClient() {
        }
        
        public UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string user, string pass) {
            return base.Channel.Login(user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string user, string pass) {
            return base.Channel.LoginAsync(user, pass);
        }
        
        public System.Data.DataSet LISTAUSUARIOS() {
            return base.Channel.LISTAUSUARIOS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTAUSUARIOSAsync() {
            return base.Channel.LISTAUSUARIOSAsync();
        }
        
        public System.Data.DataSet LISTAROLES() {
            return base.Channel.LISTAROLES();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTAROLESAsync() {
            return base.Channel.LISTAROLESAsync();
        }
        
        public void NUEVOUSUARIO(InterfazGUI.ServiceReference1.Usuario objP) {
            base.Channel.NUEVOUSUARIO(objP);
        }
        
        public System.Threading.Tasks.Task NUEVOUSUARIOAsync(InterfazGUI.ServiceReference1.Usuario objP) {
            return base.Channel.NUEVOUSUARIOAsync(objP);
        }
        
        public void ACTUALIZAUSUARIO(InterfazGUI.ServiceReference1.Usuario objP) {
            base.Channel.ACTUALIZAUSUARIO(objP);
        }
        
        public System.Threading.Tasks.Task ACTUALIZAUSUARIOAsync(InterfazGUI.ServiceReference1.Usuario objP) {
            return base.Channel.ACTUALIZAUSUARIOAsync(objP);
        }
        
        public void ELIMINAUSUARIO(InterfazGUI.ServiceReference1.Usuario objP) {
            base.Channel.ELIMINAUSUARIO(objP);
        }
        
        public System.Threading.Tasks.Task ELIMINAUSUARIOAsync(InterfazGUI.ServiceReference1.Usuario objP) {
            return base.Channel.ELIMINAUSUARIOAsync(objP);
        }
        
        public System.Data.DataTable obtenerUsuario(InterfazGUI.ServiceReference1.Usuario objP) {
            return base.Channel.obtenerUsuario(objP);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> obtenerUsuarioAsync(InterfazGUI.ServiceReference1.Usuario objP) {
            return base.Channel.obtenerUsuarioAsync(objP);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IClientes")]
    public interface IClientes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/LISTACLIENTES", ReplyAction="http://tempuri.org/IClientes/LISTACLIENTESResponse")]
        System.Data.DataSet LISTACLIENTES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/LISTACLIENTES", ReplyAction="http://tempuri.org/IClientes/LISTACLIENTESResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTACLIENTESAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/LISTADISTRITOS", ReplyAction="http://tempuri.org/IClientes/LISTADISTRITOSResponse")]
        System.Data.DataSet LISTADISTRITOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/LISTADISTRITOS", ReplyAction="http://tempuri.org/IClientes/LISTADISTRITOSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTADISTRITOSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/NUEVOCLIENTE", ReplyAction="http://tempuri.org/IClientes/NUEVOCLIENTEResponse")]
        void NUEVOCLIENTE(InterfazGUI.ServiceReference1.Cliente objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/NUEVOCLIENTE", ReplyAction="http://tempuri.org/IClientes/NUEVOCLIENTEResponse")]
        System.Threading.Tasks.Task NUEVOCLIENTEAsync(InterfazGUI.ServiceReference1.Cliente objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ACTUALIZACLIENTE", ReplyAction="http://tempuri.org/IClientes/ACTUALIZACLIENTEResponse")]
        void ACTUALIZACLIENTE(InterfazGUI.ServiceReference1.Cliente objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ACTUALIZACLIENTE", ReplyAction="http://tempuri.org/IClientes/ACTUALIZACLIENTEResponse")]
        System.Threading.Tasks.Task ACTUALIZACLIENTEAsync(InterfazGUI.ServiceReference1.Cliente objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ELIMINACLIENTE", ReplyAction="http://tempuri.org/IClientes/ELIMINACLIENTEResponse")]
        void ELIMINACLIENTE(InterfazGUI.ServiceReference1.Cliente objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ELIMINACLIENTE", ReplyAction="http://tempuri.org/IClientes/ELIMINACLIENTEResponse")]
        System.Threading.Tasks.Task ELIMINACLIENTEAsync(InterfazGUI.ServiceReference1.Cliente objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/BUSCARCLIENTE", ReplyAction="http://tempuri.org/IClientes/BUSCARCLIENTEResponse")]
        System.Data.DataSet BUSCARCLIENTE(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/BUSCARCLIENTE", ReplyAction="http://tempuri.org/IClientes/BUSCARCLIENTEResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BUSCARCLIENTEAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientesChannel : InterfazGUI.ServiceReference1.IClientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesClient : System.ServiceModel.ClientBase<InterfazGUI.ServiceReference1.IClientes>, InterfazGUI.ServiceReference1.IClientes {
        
        public ClientesClient() {
        }
        
        public ClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LISTACLIENTES() {
            return base.Channel.LISTACLIENTES();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTACLIENTESAsync() {
            return base.Channel.LISTACLIENTESAsync();
        }
        
        public System.Data.DataSet LISTADISTRITOS() {
            return base.Channel.LISTADISTRITOS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTADISTRITOSAsync() {
            return base.Channel.LISTADISTRITOSAsync();
        }
        
        public void NUEVOCLIENTE(InterfazGUI.ServiceReference1.Cliente objP) {
            base.Channel.NUEVOCLIENTE(objP);
        }
        
        public System.Threading.Tasks.Task NUEVOCLIENTEAsync(InterfazGUI.ServiceReference1.Cliente objP) {
            return base.Channel.NUEVOCLIENTEAsync(objP);
        }
        
        public void ACTUALIZACLIENTE(InterfazGUI.ServiceReference1.Cliente objP) {
            base.Channel.ACTUALIZACLIENTE(objP);
        }
        
        public System.Threading.Tasks.Task ACTUALIZACLIENTEAsync(InterfazGUI.ServiceReference1.Cliente objP) {
            return base.Channel.ACTUALIZACLIENTEAsync(objP);
        }
        
        public void ELIMINACLIENTE(InterfazGUI.ServiceReference1.Cliente objP) {
            base.Channel.ELIMINACLIENTE(objP);
        }
        
        public System.Threading.Tasks.Task ELIMINACLIENTEAsync(InterfazGUI.ServiceReference1.Cliente objP) {
            return base.Channel.ELIMINACLIENTEAsync(objP);
        }
        
        public System.Data.DataSet BUSCARCLIENTE(string nombre) {
            return base.Channel.BUSCARCLIENTE(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BUSCARCLIENTEAsync(string nombre) {
            return base.Channel.BUSCARCLIENTEAsync(nombre);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMotorizados")]
    public interface IMotorizados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/LISTAMOTORIZADOS", ReplyAction="http://tempuri.org/IMotorizados/LISTAMOTORIZADOSResponse")]
        System.Data.DataSet LISTAMOTORIZADOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/LISTAMOTORIZADOS", ReplyAction="http://tempuri.org/IMotorizados/LISTAMOTORIZADOSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTAMOTORIZADOSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/NUEVOMOTORIZADO", ReplyAction="http://tempuri.org/IMotorizados/NUEVOMOTORIZADOResponse")]
        void NUEVOMOTORIZADO(InterfazGUI.ServiceReference1.Motorizado objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/NUEVOMOTORIZADO", ReplyAction="http://tempuri.org/IMotorizados/NUEVOMOTORIZADOResponse")]
        System.Threading.Tasks.Task NUEVOMOTORIZADOAsync(InterfazGUI.ServiceReference1.Motorizado objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/ACTUALIZAMOTORIZADO", ReplyAction="http://tempuri.org/IMotorizados/ACTUALIZAMOTORIZADOResponse")]
        void ACTUALIZAMOTORIZADO(InterfazGUI.ServiceReference1.Motorizado objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/ACTUALIZAMOTORIZADO", ReplyAction="http://tempuri.org/IMotorizados/ACTUALIZAMOTORIZADOResponse")]
        System.Threading.Tasks.Task ACTUALIZAMOTORIZADOAsync(InterfazGUI.ServiceReference1.Motorizado objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/ELIMINAMOTORIZADO", ReplyAction="http://tempuri.org/IMotorizados/ELIMINAMOTORIZADOResponse")]
        void ELIMINAMOTORIZADO(InterfazGUI.ServiceReference1.Motorizado objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/ELIMINAMOTORIZADO", ReplyAction="http://tempuri.org/IMotorizados/ELIMINAMOTORIZADOResponse")]
        System.Threading.Tasks.Task ELIMINAMOTORIZADOAsync(InterfazGUI.ServiceReference1.Motorizado objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/LISTADISPONIBLES", ReplyAction="http://tempuri.org/IMotorizados/LISTADISPONIBLESResponse")]
        System.Data.DataSet LISTADISPONIBLES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorizados/LISTADISPONIBLES", ReplyAction="http://tempuri.org/IMotorizados/LISTADISPONIBLESResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTADISPONIBLESAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMotorizadosChannel : InterfazGUI.ServiceReference1.IMotorizados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MotorizadosClient : System.ServiceModel.ClientBase<InterfazGUI.ServiceReference1.IMotorizados>, InterfazGUI.ServiceReference1.IMotorizados {
        
        public MotorizadosClient() {
        }
        
        public MotorizadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MotorizadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MotorizadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MotorizadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LISTAMOTORIZADOS() {
            return base.Channel.LISTAMOTORIZADOS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTAMOTORIZADOSAsync() {
            return base.Channel.LISTAMOTORIZADOSAsync();
        }
        
        public void NUEVOMOTORIZADO(InterfazGUI.ServiceReference1.Motorizado objP) {
            base.Channel.NUEVOMOTORIZADO(objP);
        }
        
        public System.Threading.Tasks.Task NUEVOMOTORIZADOAsync(InterfazGUI.ServiceReference1.Motorizado objP) {
            return base.Channel.NUEVOMOTORIZADOAsync(objP);
        }
        
        public void ACTUALIZAMOTORIZADO(InterfazGUI.ServiceReference1.Motorizado objP) {
            base.Channel.ACTUALIZAMOTORIZADO(objP);
        }
        
        public System.Threading.Tasks.Task ACTUALIZAMOTORIZADOAsync(InterfazGUI.ServiceReference1.Motorizado objP) {
            return base.Channel.ACTUALIZAMOTORIZADOAsync(objP);
        }
        
        public void ELIMINAMOTORIZADO(InterfazGUI.ServiceReference1.Motorizado objP) {
            base.Channel.ELIMINAMOTORIZADO(objP);
        }
        
        public System.Threading.Tasks.Task ELIMINAMOTORIZADOAsync(InterfazGUI.ServiceReference1.Motorizado objP) {
            return base.Channel.ELIMINAMOTORIZADOAsync(objP);
        }
        
        public System.Data.DataSet LISTADISPONIBLES() {
            return base.Channel.LISTADISPONIBLES();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTADISPONIBLESAsync() {
            return base.Channel.LISTADISPONIBLESAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMenus")]
    public interface IMenus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/LISTAMENUS", ReplyAction="http://tempuri.org/IMenus/LISTAMENUSResponse")]
        System.Data.DataSet LISTAMENUS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/LISTAMENUS", ReplyAction="http://tempuri.org/IMenus/LISTAMENUSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTAMENUSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/NUEVOMENU", ReplyAction="http://tempuri.org/IMenus/NUEVOMENUResponse")]
        void NUEVOMENU(InterfazGUI.ServiceReference1.Plato objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/NUEVOMENU", ReplyAction="http://tempuri.org/IMenus/NUEVOMENUResponse")]
        System.Threading.Tasks.Task NUEVOMENUAsync(InterfazGUI.ServiceReference1.Plato objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/ACTUALIZAMENU", ReplyAction="http://tempuri.org/IMenus/ACTUALIZAMENUResponse")]
        void ACTUALIZAMENU(InterfazGUI.ServiceReference1.Plato objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/ACTUALIZAMENU", ReplyAction="http://tempuri.org/IMenus/ACTUALIZAMENUResponse")]
        System.Threading.Tasks.Task ACTUALIZAMENUAsync(InterfazGUI.ServiceReference1.Plato objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/ELIMINAMENU", ReplyAction="http://tempuri.org/IMenus/ELIMINAMENUResponse")]
        void ELIMINAMENU(InterfazGUI.ServiceReference1.Plato objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/ELIMINAMENU", ReplyAction="http://tempuri.org/IMenus/ELIMINAMENUResponse")]
        System.Threading.Tasks.Task ELIMINAMENUAsync(InterfazGUI.ServiceReference1.Plato objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/BUSCARMENU", ReplyAction="http://tempuri.org/IMenus/BUSCARMENUResponse")]
        System.Data.DataSet BUSCARMENU(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenus/BUSCARMENU", ReplyAction="http://tempuri.org/IMenus/BUSCARMENUResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BUSCARMENUAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenusChannel : InterfazGUI.ServiceReference1.IMenus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenusClient : System.ServiceModel.ClientBase<InterfazGUI.ServiceReference1.IMenus>, InterfazGUI.ServiceReference1.IMenus {
        
        public MenusClient() {
        }
        
        public MenusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LISTAMENUS() {
            return base.Channel.LISTAMENUS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTAMENUSAsync() {
            return base.Channel.LISTAMENUSAsync();
        }
        
        public void NUEVOMENU(InterfazGUI.ServiceReference1.Plato objP) {
            base.Channel.NUEVOMENU(objP);
        }
        
        public System.Threading.Tasks.Task NUEVOMENUAsync(InterfazGUI.ServiceReference1.Plato objP) {
            return base.Channel.NUEVOMENUAsync(objP);
        }
        
        public void ACTUALIZAMENU(InterfazGUI.ServiceReference1.Plato objP) {
            base.Channel.ACTUALIZAMENU(objP);
        }
        
        public System.Threading.Tasks.Task ACTUALIZAMENUAsync(InterfazGUI.ServiceReference1.Plato objP) {
            return base.Channel.ACTUALIZAMENUAsync(objP);
        }
        
        public void ELIMINAMENU(InterfazGUI.ServiceReference1.Plato objP) {
            base.Channel.ELIMINAMENU(objP);
        }
        
        public System.Threading.Tasks.Task ELIMINAMENUAsync(InterfazGUI.ServiceReference1.Plato objP) {
            return base.Channel.ELIMINAMENUAsync(objP);
        }
        
        public System.Data.DataSet BUSCARMENU(string nombre) {
            return base.Channel.BUSCARMENU(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BUSCARMENUAsync(string nombre) {
            return base.Channel.BUSCARMENUAsync(nombre);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPedidos")]
    public interface IPedidos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/LISTAPEDIDOS", ReplyAction="http://tempuri.org/IPedidos/LISTAPEDIDOSResponse")]
        System.Data.DataSet LISTAPEDIDOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/LISTAPEDIDOS", ReplyAction="http://tempuri.org/IPedidos/LISTAPEDIDOSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTAPEDIDOSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/LISTAPEDIDOSPENDIENTES", ReplyAction="http://tempuri.org/IPedidos/LISTAPEDIDOSPENDIENTESResponse")]
        System.Data.DataSet LISTAPEDIDOSPENDIENTES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/LISTAPEDIDOSPENDIENTES", ReplyAction="http://tempuri.org/IPedidos/LISTAPEDIDOSPENDIENTESResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTAPEDIDOSPENDIENTESAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/NUEVOPEDIDO", ReplyAction="http://tempuri.org/IPedidos/NUEVOPEDIDOResponse")]
        void NUEVOPEDIDO(InterfazGUI.ServiceReference1.Pedido objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/NUEVOPEDIDO", ReplyAction="http://tempuri.org/IPedidos/NUEVOPEDIDOResponse")]
        System.Threading.Tasks.Task NUEVOPEDIDOAsync(InterfazGUI.ServiceReference1.Pedido objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/ELIMINAPEDIDO", ReplyAction="http://tempuri.org/IPedidos/ELIMINAPEDIDOResponse")]
        void ELIMINAPEDIDO(InterfazGUI.ServiceReference1.Pedido objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/ELIMINAPEDIDO", ReplyAction="http://tempuri.org/IPedidos/ELIMINAPEDIDOResponse")]
        System.Threading.Tasks.Task ELIMINAPEDIDOAsync(InterfazGUI.ServiceReference1.Pedido objP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidosChannel : InterfazGUI.ServiceReference1.IPedidos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidosClient : System.ServiceModel.ClientBase<InterfazGUI.ServiceReference1.IPedidos>, InterfazGUI.ServiceReference1.IPedidos {
        
        public PedidosClient() {
        }
        
        public PedidosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LISTAPEDIDOS() {
            return base.Channel.LISTAPEDIDOS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTAPEDIDOSAsync() {
            return base.Channel.LISTAPEDIDOSAsync();
        }
        
        public System.Data.DataSet LISTAPEDIDOSPENDIENTES() {
            return base.Channel.LISTAPEDIDOSPENDIENTES();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTAPEDIDOSPENDIENTESAsync() {
            return base.Channel.LISTAPEDIDOSPENDIENTESAsync();
        }
        
        public void NUEVOPEDIDO(InterfazGUI.ServiceReference1.Pedido objP) {
            base.Channel.NUEVOPEDIDO(objP);
        }
        
        public System.Threading.Tasks.Task NUEVOPEDIDOAsync(InterfazGUI.ServiceReference1.Pedido objP) {
            return base.Channel.NUEVOPEDIDOAsync(objP);
        }
        
        public void ELIMINAPEDIDO(InterfazGUI.ServiceReference1.Pedido objP) {
            base.Channel.ELIMINAPEDIDO(objP);
        }
        
        public System.Threading.Tasks.Task ELIMINAPEDIDOAsync(InterfazGUI.ServiceReference1.Pedido objP) {
            return base.Channel.ELIMINAPEDIDOAsync(objP);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAsignaciones")]
    public interface IAsignaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsignaciones/LISTADEASIGNACIONES", ReplyAction="http://tempuri.org/IAsignaciones/LISTADEASIGNACIONESResponse")]
        System.Data.DataSet LISTADEASIGNACIONES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsignaciones/LISTADEASIGNACIONES", ReplyAction="http://tempuri.org/IAsignaciones/LISTADEASIGNACIONESResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTADEASIGNACIONESAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsignaciones/LISTADEASIGNACIONESPENDIENTES", ReplyAction="http://tempuri.org/IAsignaciones/LISTADEASIGNACIONESPENDIENTESResponse")]
        System.Data.DataSet LISTADEASIGNACIONESPENDIENTES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsignaciones/LISTADEASIGNACIONESPENDIENTES", ReplyAction="http://tempuri.org/IAsignaciones/LISTADEASIGNACIONESPENDIENTESResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTADEASIGNACIONESPENDIENTESAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsignaciones/AGREGARASIGNACION", ReplyAction="http://tempuri.org/IAsignaciones/AGREGARASIGNACIONResponse")]
        void AGREGARASIGNACION(InterfazGUI.ServiceReference1.Asignacion objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsignaciones/AGREGARASIGNACION", ReplyAction="http://tempuri.org/IAsignaciones/AGREGARASIGNACIONResponse")]
        System.Threading.Tasks.Task AGREGARASIGNACIONAsync(InterfazGUI.ServiceReference1.Asignacion objP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsignacionesChannel : InterfazGUI.ServiceReference1.IAsignaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsignacionesClient : System.ServiceModel.ClientBase<InterfazGUI.ServiceReference1.IAsignaciones>, InterfazGUI.ServiceReference1.IAsignaciones {
        
        public AsignacionesClient() {
        }
        
        public AsignacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsignacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsignacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsignacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LISTADEASIGNACIONES() {
            return base.Channel.LISTADEASIGNACIONES();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTADEASIGNACIONESAsync() {
            return base.Channel.LISTADEASIGNACIONESAsync();
        }
        
        public System.Data.DataSet LISTADEASIGNACIONESPENDIENTES() {
            return base.Channel.LISTADEASIGNACIONESPENDIENTES();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTADEASIGNACIONESPENDIENTESAsync() {
            return base.Channel.LISTADEASIGNACIONESPENDIENTESAsync();
        }
        
        public void AGREGARASIGNACION(InterfazGUI.ServiceReference1.Asignacion objP) {
            base.Channel.AGREGARASIGNACION(objP);
        }
        
        public System.Threading.Tasks.Task AGREGARASIGNACIONAsync(InterfazGUI.ServiceReference1.Asignacion objP) {
            return base.Channel.AGREGARASIGNACIONAsync(objP);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHistoriales")]
    public interface IHistoriales {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoriales/LISTAHISTORIAL", ReplyAction="http://tempuri.org/IHistoriales/LISTAHISTORIALResponse")]
        System.Data.DataSet LISTAHISTORIAL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoriales/LISTAHISTORIAL", ReplyAction="http://tempuri.org/IHistoriales/LISTAHISTORIALResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LISTAHISTORIALAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoriales/AGREGARHISTORIAL", ReplyAction="http://tempuri.org/IHistoriales/AGREGARHISTORIALResponse")]
        void AGREGARHISTORIAL(InterfazGUI.ServiceReference1.Historial objP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoriales/AGREGARHISTORIAL", ReplyAction="http://tempuri.org/IHistoriales/AGREGARHISTORIALResponse")]
        System.Threading.Tasks.Task AGREGARHISTORIALAsync(InterfazGUI.ServiceReference1.Historial objP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistorialesChannel : InterfazGUI.ServiceReference1.IHistoriales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistorialesClient : System.ServiceModel.ClientBase<InterfazGUI.ServiceReference1.IHistoriales>, InterfazGUI.ServiceReference1.IHistoriales {
        
        public HistorialesClient() {
        }
        
        public HistorialesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistorialesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistorialesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistorialesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LISTAHISTORIAL() {
            return base.Channel.LISTAHISTORIAL();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LISTAHISTORIALAsync() {
            return base.Channel.LISTAHISTORIALAsync();
        }
        
        public void AGREGARHISTORIAL(InterfazGUI.ServiceReference1.Historial objP) {
            base.Channel.AGREGARHISTORIAL(objP);
        }
        
        public System.Threading.Tasks.Task AGREGARHISTORIALAsync(InterfazGUI.ServiceReference1.Historial objP) {
            return base.Channel.AGREGARHISTORIALAsync(objP);
        }
    }
}
